arcoiro/__init__.py
# -*- coding: utf-8 -*-

from flask import Flask

from arcoiro.views import views

def create_app():
    app = Flask(__name__)
    app.config.setdefault('TAGS', ['bola', 'ball', 'arcoiro', 'arco-iris',
                                   'rainbow', 'flor', 'flower', 'raquete',
                                   'calcinha', 'violao', 'buzina'])
    app.config.from_envvar('ARCOIRO_SETTINGS')
    app.register_blueprint(views)
    return app


if __name__ == '__main__':
    create_app().run(debug=True)

arcoiro/providers/__init__.py
import os
from abc import ABCMeta, abstractmethod, abstractproperty
from flask import current_app
from werkzeug.contrib.cache import FileSystemCache


class BaseProvider(object):

    __metaclass__ = ABCMeta

    def __init__(self, cache_dir=None, default_timeout=60 * 60 * 24,
                 api_key=None):
        # store it in cache for 1 day. using file system cache because
        # memcached is too mainstream. :)
        self.cache = FileSystemCache(cache_dir=cache_dir or '/tmp/__arcoiro__',
                                     default_timeout=default_timeout)
        self._api_key = api_key

    @abstractproperty
    def name(self):
        pass

    @abstractproperty
    def url(self):
        pass

    @abstractmethod
    def get_urls_from_tag(self, tag):
        pass

    @property
    def display_name(self):
        return self.name

    @property
    def api_key(self):
        if self._api_key is not None:
            return self._api_key
        config_key = '%s_API_KEY' % self.name.upper()
        key = current_app.config.get(config_key)
        if key is None:
            raise RuntimeError('%s not defined!' % config_key)
        return key

    def get_cached_urls_from_tag(self, tag):
        cache_key = '%s:%s' % (self.name, tag)
        urls = self.cache.get(cache_key)
        if urls is not None:
            return urls
        urls = self.get_urls_from_tag(tag)
        if urls is None:
            return None
        self.cache.set(cache_key, urls)
        return urls


def list_providers():
    cwd = os.path.dirname(os.path.abspath(__file__))
    for filename in os.listdir(cwd):
        if filename.startswith('_'):
            continue
        if not filename.endswith('.py'):
            continue
        __import__('%s.%s' % (__name__, filename.rstrip('.py')))
    return BaseProvider.__subclasses__()

arcoiro/views.py
import random
from flask import Blueprint, abort, current_app, render_template

from arcoiro.providers import list_providers

views = Blueprint('views', __name__)


@views.route('/')
def home():
    tag = random.choice(current_app.config['TAGS'])
    provider = random.choice(list_providers())



    urls = provider().get_cached_urls_from_tag(tag)
    if urls is None:
        abort(404)
    url = random.choice(urls)
    return render_template('frameset.html', url=url)


@views.route('/footer')
def footer():
    return render_template('footer.html')

arcoiro/templates/footer.html
<html>
    <head>
        <style type="text/css">
            p {
                font-family: monospace, serif;
                font-size: 10px;
                font-weight: bold;
                margin: 4px auto;
                text-align: center;
            }
        </style>
    <body>
        <p>
            arcoiro - faz aquilo que você sabe! Não entendeu!?
            <a href="http://www.youtube.com/watch?v=mpXShHdQGcQ"
                target="_blank">Clique aqui!</a>
        </p>
        <p>
            Este site não hospeda nenhum arquivo. Todo o conteúdo é obtido
            diretamente do <a href="http://tumblr.com">tumblr.com</a>, e é de
            responsabilidade de seus autores.
        </p>
    </body>
</html>

arcoiro/templates/frameset.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN">
<html>
    <head>
        <title>arcoiro - faz aquilo que você sabe!</title>
        <meta http-equiv="cache-control" content="no-cache">
        <meta http-equiv="pragma" content="no-cache">
    </head>
    <frameset rows="*,50" border="0" frameborder="no" framespacing="0">
        <frame src="{{ url }}" noresize>
        <frame src="{{ url_for('views.footer') }}">
    </frameset>
</html>